import { describe, expect, it } from 'vitest'
import { createArchivePrBody } from '../scripts/openspec-archive-closure'
import { validatePrBodyPolicy } from '../scripts/pr-body-policy'

describe('OpenSpec archive closure helper', () => {
  it('generates a PR body accepted by local governance policy', () => {
    const body = createArchivePrBody(['harden-agent-archive-closure'])

    expect(body).toContain('## Linked Artifacts')
    expect(body).toContain('Generated by `bun run openspec:archive-closure`.')
    expect(
      validatePrBodyPolicy({
        body,
        changedFiles: ['openspec/changes/archive/generated-harden-agent-archive-closure/tasks.md'],
        title: 'docs(openspec): archive completed changes',
      }),
    ).toEqual([])
  })
})
