import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { validatePrBodyPolicy } from './pr-body-policy'

export interface ArchiveClosureOptions {
  applySpecs: boolean
  bodyFile?: string
  changeIds: string[]
  title: string
}

export interface ArchiveClosureDeps {
  changeDirExists?: ChangeDirChecker
  emitBody?: BodyEmitter
  run?: CommandRunner
}

export interface OpenSpecApplyInstructions {
  changeName: string
  progress: OpenSpecTaskProgress
}

export interface OpenSpecTaskProgress {
  complete: number
  remaining: number
  total: number
}

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

export function createArchivePrBody(changeIds: string[]): string {
  const openSpecList = changeIds.map(changeId => `\`${changeId}\``).join(', ')

  return `## Summary

Archive completed OpenSpec changes ${openSpecList} after their implementation PRs merged, and close the agent-driven archive follow-up with repository validation.

## Linked Artifacts

- Issue:
- ADR:
- OpenSpec: ${openSpecList}
- Discussion:

## Validation

- [x] \`bun run openspec:validate\`
- [ ] \`bun run memory:check\`
- [ ] \`bun run lint\`
- [ ] \`bun run format:check\`
- [ ] \`bun run typecheck\`
- [ ] \`bun run test\` (if behavior changed)
- [ ] Not run, explained below

## Release Intent

- Release: not applicable - OpenSpec archive closure only

## Release Summary

- Not applicable - OpenSpec archive closure does not produce a release entry.

## Docs Updated

- [ ] Not needed
- [ ] \`docs/...\`
- [x] \`openspec/...\`
- [ ] Follow-up issue or OpenSpec change created instead

## Scope Check

- [x] I did not add a new ad hoc root-level Markdown file.
- [x] I updated the relevant issue, ADR, spec, runbook, or captured the missing doc work as follow-up.
- [x] I did not silently expand project scope without recording it explicitly.

## Closure Check

- [x] Working tree was clean before archive closure started.
- [ ] Branch was pushed and this PR is the active delivery artifact.
- [x] OpenSpec change is already archived or queued for agent-driven archive closure.
- [x] Release is not applicable, delegated to release automation, or verified.

## Notes

- Generated by \`bun run openspec:archive-closure\`.
`
}

if (import.meta.main) {
  const options = parseArgs(process.argv.slice(2))
  await runArchiveClosure(options)
}

export async function runArchiveClosure(options: ArchiveClosureOptions, deps: ArchiveClosureDeps = {}): Promise<void> {
  const run = deps.run ?? runChecked
  const emitBody = deps.emitBody ?? writeArchivePrBody

  if (options.changeIds.length === 0) {
    throw new Error('At least one OpenSpec change id is required.')
  }

  for (const changeId of options.changeIds) {
    assertOpenSpecArchiveReady(changeId, run)
  }

  for (const changeId of options.changeIds) {
    archiveChange(changeId, options.applySpecs, deps)
  }

  run('bun', ['run', 'openspec:validate'])

  const body = createArchivePrBody(options.changeIds)
  const bodyIssues = validatePrBodyPolicy({
    body,
    changedFiles: options.changeIds.map(changeId => `openspec/specs/${changeId}/spec.md`),
    title: options.title,
  })

  if (bodyIssues.length > 0) {
    throw new Error(`Generated archive PR body failed policy validation:\n${bodyIssues.join('\n')}`)
  }

  await emitBody(body, options.bodyFile)
}

async function writeArchivePrBody(body: string, bodyFile?: string): Promise<void> {
  if (!bodyFile) {
    console.log(body)
    return
  }

  const outputPath = resolve(rootDir, bodyFile)
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, body)
  console.log(`Archive PR body written to ${bodyFile}`)
}

export function assertOpenSpecTasksComplete(changeName: string, progress: OpenSpecTaskProgress): void {
  const isComplete = progress.total > 0 && progress.complete === progress.total && progress.remaining === 0

  if (!isComplete) {
    throw new Error(
      `OpenSpec change "${changeName}" has incomplete tasks (${progress.complete}/${progress.total}, ${progress.remaining} remaining). Complete its task list before archiving.`,
    )
  }
}

type BodyEmitter = (body: string, bodyFile?: string) => Promise<void>

type ChangeDirChecker = (changeId: string) => boolean

type CommandRunner = (command: string, args: string[], options?: { capture?: boolean }) => string

export function assertOpenSpecArchiveReady(changeId: string, run: CommandRunner = runChecked): void {
  const result = run('openspec', ['instructions', 'apply', '--change', changeId, '--json'], { capture: true })
  const instructions = parseOpenSpecApplyInstructions(result, changeId)
  assertOpenSpecTasksComplete(instructions.changeName, instructions.progress)
}

export function parseOpenSpecApplyInstructions(output: string, changeId: string): OpenSpecApplyInstructions {
  const jsonStart = output.indexOf('{')
  const jsonEnd = output.lastIndexOf('}')

  if (jsonStart === -1 || jsonEnd === -1 || jsonEnd < jsonStart) {
    throw new Error(`Could not parse OpenSpec apply instructions for "${changeId}".`)
  }

  const instructions = JSON.parse(output.slice(jsonStart, jsonEnd + 1)) as OpenSpecApplyInstructions

  if (
    typeof instructions.changeName !== 'string' ||
    typeof instructions.progress?.complete !== 'number' ||
    typeof instructions.progress?.remaining !== 'number' ||
    typeof instructions.progress?.total !== 'number'
  ) {
    throw new Error(`OpenSpec apply instructions for "${changeId}" have invalid task progress.`)
  }

  if (instructions.changeName !== changeId) {
    throw new Error(
      `OpenSpec apply instructions change mismatch: requested "${changeId}", received "${instructions.changeName}".`,
    )
  }

  return instructions
}

function archiveChange(changeId: string, applySpecs: boolean, deps: ArchiveClosureDeps = {}): void {
  const run = deps.run ?? runChecked
  const changeDirExists = deps.changeDirExists ?? openSpecChangeDirExists

  const args = ['archive', '--yes', changeId]
  if (!applySpecs) args.push('--skip-specs')

  const output = run('openspec', args)
  assertChangeArchived(changeId, output, changeDirExists)
}

/**
 * `openspec archive` exits 0 when it aborts gracefully (for example when a spec
 * delta header no longer matches), so the exit code alone cannot prove the
 * change was archived. Verify the outcome instead, and surface the underlying
 * reason so the operator sees which change failed and why.
 */
export function assertChangeArchived(
  changeId: string,
  output: string,
  changeDirExists: ChangeDirChecker = openSpecChangeDirExists,
): void {
  const abortReasons = findArchiveAbortReasons(output)
  const stillActive = changeDirExists(changeId)

  if (!stillActive && abortReasons.length === 0) return

  const cause = stillActive
    ? `\`openspec archive\` left \`openspec/changes/${changeId}\` in place`
    : '`openspec archive` reported an aborted run'
  const details = abortReasons.length > 0 ? `\n${abortReasons.join('\n')}` : ''

  throw new Error(
    `OpenSpec change "${changeId}" was not archived: ${cause}. Resolve the underlying archive failure and rerun archive closure.${details}`,
  )
}

function findArchiveAbortReasons(output: string): string[] {
  return output
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.startsWith('Aborted.') || line.includes(' failed for '))
}

function openSpecChangeDirExists(changeId: string): boolean {
  return existsSync(resolve(rootDir, 'openspec/changes', changeId))
}

function runChecked(command: string, args: string[], options: { capture?: boolean } = {}): string {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    encoding: 'utf8',
    env: process.env,
  })

  const output = `${result.stdout ?? ''}${result.stderr ?? ''}`

  if (!options.capture && output.trim()) {
    process.stdout.write(output)
    if (!output.endsWith('\n')) process.stdout.write('\n')
  }

  if (result.status !== 0) {
    if (options.capture && output.trim()) process.stderr.write(output)
    throw new Error(`Command failed: ${command} ${args.join(' ')}`)
  }

  return output
}

function parseArgs(args: string[]): ArchiveClosureOptions {
  const options: ArchiveClosureOptions = {
    applySpecs: false,
    changeIds: [],
    title: 'docs(openspec): archive completed changes',
  }

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index]
    const nextValue = args[index + 1]

    if (arg === '--apply-specs') {
      options.applySpecs = true
    } else if (arg === '--body-file' && nextValue) {
      options.bodyFile = nextValue
      index += 1
    } else if (arg === '--title' && nextValue) {
      options.title = nextValue
      index += 1
    } else if (arg.startsWith('--')) {
      throw new Error(`Unknown argument: ${arg}`)
    } else {
      options.changeIds.push(arg)
    }
  }

  return options
}
