import { spawnSync } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { validatePrBodyPolicy } from './pr-body-policy'

interface ArchiveClosureOptions {
  applySpecs: boolean
  bodyFile?: string
  changeIds: string[]
  title: string
}

interface OpenSpecStatus {
  changeName: string
  isComplete: boolean
}

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')

export function createArchivePrBody(changeIds: string[]): string {
  const openSpecList = changeIds.map(changeId => `\`${changeId}\``).join(', ')

  return `## Summary

Archive completed OpenSpec changes ${openSpecList} after their implementation PRs merged, and close the agent-driven archive follow-up with repository validation.

## Linked Artifacts

- Issue:
- ADR:
- OpenSpec: ${openSpecList}
- Discussion:

## Validation

- [x] \`bun run openspec:validate\`
- [ ] \`bun run memory:check\`
- [ ] \`bun run lint\`
- [ ] \`bun run format:check\`
- [ ] \`bun run typecheck\`
- [ ] \`bun run test\` (if behavior changed)
- [ ] Not run, explained below

## Release Intent

- Release: not applicable - OpenSpec archive closure only

## Docs Updated

- [ ] Not needed
- [ ] \`docs/...\`
- [x] \`openspec/...\`
- [ ] Follow-up issue or OpenSpec change created instead

## Scope Check

- [x] I did not add a new ad hoc root-level Markdown file.
- [x] I updated the relevant issue, ADR, spec, runbook, or captured the missing doc work as follow-up.
- [x] I did not silently expand project scope without recording it explicitly.

## Closure Check

- [x] Working tree was clean before archive closure started.
- [ ] Branch was pushed and this PR is the active delivery artifact.
- [x] OpenSpec change is already archived or queued for agent-driven archive closure.
- [x] Release is not applicable, delegated to release automation, or verified.

## Notes

- Generated by \`bun run openspec:archive-closure\`.
`
}

if (import.meta.main) {
  const options = parseArgs(process.argv.slice(2))
  await runArchiveClosure(options)
}

async function runArchiveClosure(options: ArchiveClosureOptions): Promise<void> {
  if (options.changeIds.length === 0) {
    throw new Error('At least one OpenSpec change id is required.')
  }

  for (const changeId of options.changeIds) {
    const status = readOpenSpecStatus(changeId)
    if (!status.isComplete) {
      throw new Error(
        `OpenSpec change "${status.changeName}" is not complete. Complete its task list before archiving.`,
      )
    }
  }

  for (const changeId of options.changeIds) {
    archiveChange(changeId, options.applySpecs)
  }

  runChecked('bun', ['run', 'openspec:validate'])

  const body = createArchivePrBody(options.changeIds)
  const bodyIssues = validatePrBodyPolicy({
    body,
    changedFiles: options.changeIds.map(changeId => `openspec/changes/archive/generated-${changeId}/tasks.md`),
    title: options.title,
  })

  if (bodyIssues.length > 0) {
    throw new Error(`Generated archive PR body failed policy validation:\n${bodyIssues.join('\n')}`)
  }

  if (options.bodyFile) {
    const outputPath = resolve(rootDir, options.bodyFile)
    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(outputPath, body)
    console.log(`Archive PR body written to ${options.bodyFile}`)
  } else {
    console.log(body)
  }
}

function readOpenSpecStatus(changeId: string): OpenSpecStatus {
  const result = runChecked('bun', ['run', 'openspec:status', '--', '--change', changeId], { capture: true })
  const jsonStart = result.indexOf('{')
  const jsonEnd = result.lastIndexOf('}')

  if (jsonStart === -1 || jsonEnd === -1 || jsonEnd < jsonStart) {
    throw new Error(`Could not parse OpenSpec status for "${changeId}".`)
  }

  return JSON.parse(result.slice(jsonStart, jsonEnd + 1)) as OpenSpecStatus
}

function archiveChange(changeId: string, applySpecs: boolean): void {
  const args = ['run', 'openspec:archive', '--', changeId]
  if (!applySpecs) args.push('--skip-specs')

  runChecked('bun', args)
}

function runChecked(command: string, args: string[], options: { capture?: boolean } = {}): string {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    encoding: 'utf8',
    env: process.env,
  })

  const output = `${result.stdout ?? ''}${result.stderr ?? ''}`

  if (!options.capture && output.trim()) {
    process.stdout.write(output)
    if (!output.endsWith('\n')) process.stdout.write('\n')
  }

  if (result.status !== 0) {
    if (options.capture && output.trim()) process.stderr.write(output)
    throw new Error(`Command failed: ${command} ${args.join(' ')}`)
  }

  return output
}

function parseArgs(args: string[]): ArchiveClosureOptions {
  const options: ArchiveClosureOptions = {
    applySpecs: false,
    changeIds: [],
    title: 'docs(openspec): archive completed changes',
  }

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index]
    const nextValue = args[index + 1]

    if (arg === '--apply-specs') {
      options.applySpecs = true
    } else if (arg === '--body-file' && nextValue) {
      options.bodyFile = nextValue
      index += 1
    } else if (arg === '--title' && nextValue) {
      options.title = nextValue
      index += 1
    } else if (arg.startsWith('--')) {
      throw new Error(`Unknown argument: ${arg}`)
    } else {
      options.changeIds.push(arg)
    }
  }

  return options
}
