import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { basename, dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const defaultCatalogDir = resolve(rootDir, 'src/agents/catalog')
const defaultCatalogDataOutputPath = resolve(rootDir, 'src/agents/generated/catalog-data.ts')
const defaultCatalogAgentsOutputPath = resolve(rootDir, 'src/agents/generated/catalog-agents.ts')
const defaultCatalogAdapterPath = resolve(rootDir, 'src/agents/catalog.ts')

interface CatalogEntryFile {
  fileName: string
  name: string
}

interface AgentCatalogManifestOptions {
  catalogAdapterPath?: string
  catalogAgentsOutputPath?: string
  catalogDataOutputPath?: string
  catalogDir?: string
}

export interface AgentCatalogManifest {
  catalogAgentsSource: string
  catalogDataSource: string
  entries: CatalogEntryFile[]
}

export async function writeAgentCatalogManifest(options: AgentCatalogManifestOptions = {}): Promise<void> {
  const manifest = await buildAgentCatalogManifest(options)
  const catalogDataOutputPath = options.catalogDataOutputPath ?? defaultCatalogDataOutputPath
  const catalogAgentsOutputPath = options.catalogAgentsOutputPath ?? defaultCatalogAgentsOutputPath

  await mkdir(dirname(catalogDataOutputPath), { recursive: true })
  await writeFile(catalogDataOutputPath, manifest.catalogDataSource)
  await writeFile(catalogAgentsOutputPath, manifest.catalogAgentsSource)
}

export async function buildAgentCatalogManifest(
  options: AgentCatalogManifestOptions = {},
): Promise<AgentCatalogManifest> {
  const catalogDir = options.catalogDir ?? defaultCatalogDir
  const catalogDataOutputPath = options.catalogDataOutputPath ?? defaultCatalogDataOutputPath
  const catalogAgentsOutputPath = options.catalogAgentsOutputPath ?? defaultCatalogAgentsOutputPath
  const catalogAdapterPath = options.catalogAdapterPath ?? defaultCatalogAdapterPath
  const entries = await readCatalogEntries(catalogDir)

  return {
    catalogAgentsSource: renderCatalogAgentsManifest(entries, catalogAgentsOutputPath, catalogAdapterPath),
    catalogDataSource: renderCatalogDataManifest(entries, catalogDataOutputPath, catalogDir),
    entries,
  }
}

export async function readCatalogEntries(catalogDir: string = defaultCatalogDir): Promise<CatalogEntryFile[]> {
  const dirEntries = await readdir(catalogDir, { withFileTypes: true })
  const files = dirEntries
    .filter(entry => entry.isFile() && entry.name.endsWith('.json'))
    .map(entry => entry.name)
    .sort((left, right) => left.localeCompare(right))

  if (files.length === 0) {
    throw new Error(`No agent catalog JSON files found in ${catalogDir}.`)
  }

  const entries: CatalogEntryFile[] = []

  for (const fileName of files) {
    const filePath = resolve(catalogDir, fileName)
    const rawValue = await readFile(filePath, 'utf8')
    const parsedValue = JSON.parse(rawValue) as unknown
    const expectedName = basename(fileName, '.json')

    if (typeof parsedValue !== 'object' || parsedValue === null || !('name' in parsedValue)) {
      throw new Error(`Catalog file ${fileName} must contain an object with a string name.`)
    }

    const name = (parsedValue as { name?: unknown }).name
    if (typeof name !== 'string' || name.length === 0) {
      throw new Error(`Catalog file ${fileName} must contain a non-empty string name.`)
    }

    if (name !== expectedName) {
      throw new Error(`Catalog filename ${fileName} must match entry name ${name}.`)
    }

    entries.push({ fileName, name })
  }

  return entries
}

function renderCatalogDataManifest(
  entries: CatalogEntryFile[],
  catalogDataOutputPath: string,
  catalogDir: string,
): string {
  const imports = entries
    .map((entry, index) => {
      const importPath = getImportPath(catalogDataOutputPath, resolve(catalogDir, entry.fileName))
      return `import agent${index} from '${importPath}'`
    })
    .join('\n')
  const values = entries.map((_entry, index) => `  agent${index},`).join('\n')

  return `// Generated by scripts/write-agent-catalog-manifest.ts. Do not edit by hand.\n\n${imports}\n\nexport const catalogData = [\n${values}\n]\n`
}

function renderCatalogAgentsManifest(
  entries: CatalogEntryFile[],
  catalogAgentsOutputPath: string,
  catalogAdapterPath: string,
): string {
  const catalogImportPath = getImportPath(catalogAgentsOutputPath, catalogAdapterPath).replace(/\.ts$/, '')
  const exports = entries
    .map(entry => `export const ${toIdentifier(entry.name)} = getCatalogAgent('${entry.name}')`)
    .join('\n')

  return `// Generated by scripts/write-agent-catalog-manifest.ts. Do not edit by hand.\n\nimport { getCatalogAgent } from '${catalogImportPath}'\n\n${exports}\n`
}

function getImportPath(fromFilePath: string, toFilePath: string): string {
  const normalizedPath = relative(dirname(fromFilePath), toFilePath).replaceAll('\\', '/')
  return normalizedPath.startsWith('.') ? normalizedPath : `./${normalizedPath}`
}

function toIdentifier(name: string): string {
  const identifier = name.replace(/-([a-z0-9])/g, (_match, char: string) => char.toUpperCase())
  if (!/^[a-zA-Z_$][\w$]*$/.test(identifier)) {
    throw new Error(`Catalog entry ${name} cannot be represented as a TypeScript named export.`)
  }

  return identifier
}

if (import.meta.main) {
  await writeAgentCatalogManifest()
}
