import type { AgentDefinition } from '../src/agents/types'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import process from 'node:process'
import { getAllAgents } from '../src/agents'

const target = join(process.cwd(), 'src', 'core', 'generated', 'agent-catalog.ts')
const catalog = getAllAgents().map(projectCoreAgent)
const source = [
  '// Generated by scripts/write-core-agent-catalog.ts. Do not edit by hand.',
  '',
  "import type { AgentDefinition } from '../../agents/types'",
  '',
  `export const coreAgentCatalog: readonly AgentDefinition[] = ${JSON.stringify(catalog, null, 2)}`,
  '',
].join('\n')

await mkdir(dirname(target), { recursive: true })
await writeFile(target, source)

function projectCoreAgent(agent: AgentDefinition): AgentDefinition {
  if (typeof agent.versionProbe?.parser === 'function') {
    throw new Error(`Core catalog generation cannot serialize the version parser for ${agent.name}.`)
  }
  return {
    binaryName: agent.binaryName,
    displayName: agent.displayName,
    homepage: agent.homepage,
    ...(agent.lookupAliases?.length ? { lookupAliases: [...agent.lookupAliases] } : {}),
    name: agent.name,
    ...(agent.packages ? { packages: { ...agent.packages } } : {}),
    platforms: Object.fromEntries(
      Object.entries(agent.platforms).map(([platform, methods]) => [
        platform,
        methods?.map(method => ({
          ...(method.binaryName ? { binaryName: method.binaryName } : {}),
          ...(method.command ? { command: method.command } : {}),
          ...(method.packageInstallArgs ? { packageInstallArgs: [...method.packageInstallArgs] } : {}),
          ...(method.packageName ? { packageName: method.packageName } : {}),
          ...(method.packageTargetKind ? { packageTargetKind: method.packageTargetKind } : {}),
          type: method.type,
        })),
      ]),
    ) as AgentDefinition['platforms'],
    ...(agent.versionProbe ? { versionProbe: { command: agent.versionProbe.command } } : {}),
  }
}
