import type { CatalogSourceEntry, NormalizedInstallCandidate } from '../src/agents/schema'
import type { AgentDefinition } from '../src/agents/types'
import type { ProviderExecutionEffect } from '../src/providers/types'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import process from 'node:process'
import { format } from 'oxfmt'
import { getAllAgents } from '../src/agents'
import { readCatalogEntries } from './write-agent-catalog-manifest'

const discoveryTarget = join(process.cwd(), 'src', 'core', 'generated', 'agent-catalog.ts')
const mutationRecipeTarget = join(process.cwd(), 'src', 'core', 'generated', 'mutation-recipe-catalog.ts')
const formatOptions = {
  printWidth: 120,
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
} as const

export async function writeCoreAgentCatalogs(): Promise<void> {
  const entries = await readCatalogEntries()
  const [discoverySource, mutationRecipeSource] = await Promise.all([
    format('agent-catalog.ts', renderCoreAgentCatalogSource(getAllAgents()), formatOptions),
    format(
      'mutation-recipe-catalog.ts',
      renderCoreMutationRecipeCatalogSource(entries.map(entry => entry.source)),
      formatOptions,
    ),
  ])
  await mkdir(dirname(discoveryTarget), { recursive: true })
  await Promise.all([
    writeFile(discoveryTarget, discoverySource.code),
    writeFile(mutationRecipeTarget, mutationRecipeSource.code),
  ])
}

export function renderCoreAgentCatalogSource(agents: readonly AgentDefinition[]): string {
  const catalog = agents.map(projectCoreAgent)
  return [
    '// Generated by scripts/write-core-agent-catalog.ts. Do not edit by hand.',
    '',
    "import type { AgentDefinition } from '../../agents/types'",
    '',
    `export const coreAgentCatalog: readonly AgentDefinition[] = ${JSON.stringify(catalog, null, 2)}`,
    '',
  ].join('\n')
}

export function renderCoreMutationRecipeCatalogSource(entries: readonly CatalogSourceEntry[]): string {
  const catalog = projectCoreMutationRecipeCatalog(entries)
  return [
    '// Generated by scripts/write-core-agent-catalog.ts from the validated normalized catalog. Do not edit by hand.',
    '',
    "import type { CoreAgentMutationRecipes } from '../mutation-recipe-catalog'",
    '',
    `export const coreMutationRecipeCatalog = ${JSON.stringify(catalog, null, 2)} as const satisfies readonly CoreAgentMutationRecipes[]`,
    '',
  ].join('\n')
}

export function projectCoreMutationRecipeCatalog(
  entries: readonly CatalogSourceEntry[],
): readonly CoreAgentMutationRecipesProjection[] {
  return entries.map(entry => ({
    name: entry.name,
    platforms: Object.fromEntries(
      Object.entries(entry.platforms).map(([platform, candidates]) => [
        platform,
        candidates?.map(candidate => {
          if ('type' in candidate) {
            throw new Error(`${entry.name} still uses legacy ${candidate.type} catalog methods on ${platform}.`)
          }
          return projectMutationRecipe(candidate)
        }),
      ]),
    ),
  }))
}

interface CoreAgentMutationRecipesProjection {
  readonly name: string
  readonly platforms: Readonly<Record<string, readonly CoreMutationRecipeProjection[] | undefined>>
}

interface CoreMutationRecipeProjection {
  readonly probes?: readonly string[]
  readonly provider: NormalizedInstallCandidate['provider']
  readonly target: {
    readonly arguments?: readonly string[]
    readonly binaryName?: string
    readonly effect?: ProviderExecutionEffect
    readonly id: string
    readonly kind: string
  }
}

function projectMutationRecipe(candidate: NormalizedInstallCandidate): CoreMutationRecipeProjection {
  const target = candidate.target
  const effect =
    candidate.provider === 'script' || candidate.provider === 'binary' ? candidate.target.effect : undefined
  return {
    ...(candidate.probes ? { probes: [...candidate.probes] } : {}),
    provider: candidate.provider,
    target: {
      ...(target.arguments ? { arguments: [...target.arguments] } : {}),
      ...(target.binaryName ? { binaryName: target.binaryName } : {}),
      ...(effect ? { effect: cloneExecutionEffect(effect) } : {}),
      id: target.id,
      kind: target.kind,
    },
  }
}

function cloneExecutionEffect(effect: unknown): ProviderExecutionEffect {
  if (!effect || typeof effect !== 'object' || !('kind' in effect) || !('command' in effect)) {
    throw new Error('Normalized script or binary recipe is missing its execution effect.')
  }
  if (effect.kind === 'shell-script' && typeof effect.command === 'string') {
    return { command: effect.command, kind: effect.kind }
  }
  if (
    effect.kind === 'executable' &&
    Array.isArray(effect.command) &&
    effect.command.every(argument => typeof argument === 'string')
  ) {
    return { command: [...effect.command], kind: effect.kind }
  }
  throw new Error('Normalized script or binary recipe contains an invalid execution effect.')
}

function projectCoreAgent(agent: AgentDefinition): AgentDefinition {
  if (typeof agent.versionProbe?.parser === 'function') {
    throw new Error(`Core catalog generation cannot serialize the version parser for ${agent.name}.`)
  }
  return {
    binaryName: agent.binaryName,
    displayName: agent.displayName,
    homepage: agent.homepage,
    ...(agent.lookupAliases?.length ? { lookupAliases: [...agent.lookupAliases] } : {}),
    name: agent.name,
    ...(agent.packages ? { packages: { ...agent.packages } } : {}),
    platforms: Object.fromEntries(
      Object.entries(agent.platforms).map(([platform, methods]) => [
        platform,
        methods?.map(method => ({
          ...(method.binaryName ? { binaryName: method.binaryName } : {}),
          ...(method.command ? { command: method.command } : {}),
          ...(method.packageInstallArgs ? { packageInstallArgs: [...method.packageInstallArgs] } : {}),
          ...(method.packageName ? { packageName: method.packageName } : {}),
          ...(method.packageTargetKind ? { packageTargetKind: method.packageTargetKind } : {}),
          type: method.type,
        })),
      ]),
    ) as AgentDefinition['platforms'],
    ...(agent.versionProbe ? { versionProbe: { command: agent.versionProbe.command } } : {}),
  }
}

if (import.meta.main) await writeCoreAgentCatalogs()
